### ISSUE TITLE
Plugin name completion is failed in Neovim

### ISSUE THREAD

**Issue by kawarimidoll** [4513ECHO/vim-readme-viewer#1]
In Neovim, E117 is occurred when try to complete the plugin name from the suggestions.
Neovim does not have `matchfuzzy()` currently...
ref: https://github.com/neovim/neovim/pull/12995

![Kapture 2021-12-04 at 18 24 42](https://user-images.githubusercontent.com/8146876/144704591-9fb1da89-c598-45a9-a8e5-e3c53a4fe3c7.gif)

**Comment by 4513ECHO** [comment]
Thank you. I fixed.

**Comment by kawarimidoll** [comment]
Thank you for the quick response ✨
